"""Type information for the compiled surface.

Held against the module itself by tests/test_surface.py, so a class added
to one and not the other fails the suite rather than going unnoticed.
"""

from types import TracebackType
from typing import Callable, Self, Sequence

class Lagged(Exception):
    """A subscriber fell behind and what it asked for was overwritten."""

class Contended(Exception):
    """Another live process holds the lease and has not been quiet long."""

class WrongLane(Exception):
    """The key belongs to a different lane and must be written through it."""

def boundary_note() -> str: ...

# The transports this wheel was built with. The Sens-O-Matic link is
# always there; each bridge is present only when its feature was built.
transports: list[str]

# Whether this extension was built against an interpreter with no lock.
free_threaded: bool

# What each optional transport brings, so a caller can tell a wheel
# built without one from a name that never existed.
OPTIONAL_BY_TRANSPORT: dict[str, tuple[str, ...]]

# Shared state.

class Atomic:
    def __init__(self, path: str, init: int = 0) -> None: ...
    @staticmethod
    def open(path: str) -> Atomic: ...
    def load(self, order: str = "seq_cst") -> int: ...
    def store(self, value: int, order: str = "seq_cst") -> None: ...
    def fetch_add(self, value: int = 1, order: str = "seq_cst") -> int: ...
    def fetch_sub(self, value: int = 1, order: str = "seq_cst") -> int: ...
    def fetch_or(self, value: int, order: str = "seq_cst") -> int: ...
    def fetch_and(self, value: int, order: str = "seq_cst") -> int: ...
    def fetch_xor(self, value: int, order: str = "seq_cst") -> int: ...
    def swap(self, value: int, order: str = "seq_cst") -> int: ...
    def compare_exchange(
        self, expected: int, new: int, order: str = "seq_cst"
    ) -> int: ...
    def fetch_add_many(self, count: int, value: int = 1, order: str = "seq_cst") -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class Region:
    def __init__(
        self, path: str, capacity: int, slot_size: int, alignment: int = 1, tag: int = 0
    ) -> None: ...
    @property
    def capacity(self) -> int: ...
    def __len__(self) -> int: ...
    def allocate(self, value: bytes) -> int: ...
    def get(self, index: int) -> bytes: ...
    def set(self, index: int, value: bytes) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class Cell:
    def __init__(self, path: str, value_size: int) -> None: ...
    @staticmethod
    def open(path: str, value_size: int) -> Cell: ...
    @property
    def value_size(self) -> int: ...
    @property
    def version(self) -> int: ...
    def get(self) -> bytes: ...
    def set(self, value: bytes) -> None: ...
    def flush(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class Vec:
    def __init__(
        self, path: str, capacity: int, element_size: int, alignment: int = 1, tag: int = 0
    ) -> None: ...
    @staticmethod
    def open(
        path: str, capacity: int, element_size: int, alignment: int = 1, tag: int = 0
    ) -> Vec: ...
    @property
    def capacity(self) -> int: ...
    @property
    def element_size(self) -> int: ...
    @property
    def writable(self) -> bool: ...
    def __len__(self) -> int: ...
    def push(self, value: bytes) -> int | None: ...
    def push_many(self, values: Sequence[bytes]) -> int: ...
    def pop(self) -> bytes | None: ...
    def get(self, index: int) -> bytes | None: ...
    def set(self, index: int, value: bytes) -> None: ...
    def read_range(self, start: int, count: int) -> bytes: ...
    def write_range(self, start: int, data: bytes) -> int: ...
    def clear(self) -> None: ...
    def flush(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class Slab:
    def __init__(
        self, path: str, capacity: int, element_size: int, alignment: int = 1, tag: int = 0
    ) -> None: ...
    @staticmethod
    def open(
        path: str, capacity: int, element_size: int, alignment: int = 1, tag: int = 0
    ) -> Slab: ...
    @staticmethod
    def open_read_only(
        path: str, capacity: int, element_size: int, alignment: int = 1, tag: int = 0
    ) -> Slab: ...
    @property
    def capacity(self) -> int: ...
    @property
    def element_size(self) -> int: ...
    @property
    def writable(self) -> bool: ...
    def __len__(self) -> int: ...
    def get(self, index: int) -> bytes: ...
    def set(self, index: int, value: bytes) -> None: ...
    def slot_version(self, index: int) -> int: ...
    def read_range(self, start: int, count: int) -> bytes: ...
    def write_range(self, start: int, data: bytes) -> int: ...
    def flush(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class HashMap:
    def __init__(self, path: str, capacity: int, key_size: int, value_size: int) -> None: ...
    @staticmethod
    def open(path: str, capacity: int, key_size: int, value_size: int) -> HashMap: ...
    @property
    def capacity(self) -> int: ...
    @property
    def key_size(self) -> int: ...
    @property
    def value_size(self) -> int: ...
    @property
    def tombstones(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: bytes) -> bool: ...
    def insert(self, key: bytes, value: bytes) -> str | None: ...
    def insert_many(self, pairs: Sequence[tuple[bytes, bytes]]) -> int: ...
    def get(self, key: bytes) -> bytes | None: ...
    def get_many(self, keys: Sequence[bytes]) -> list[bytes | None]: ...
    def remove(self, key: bytes) -> bytes | None: ...
    def compare_exchange(
        self, key: bytes, expected: bytes, new: bytes
    ) -> tuple[bool, bytes]: ...
    def clear(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class BTreeMap:
    def __init__(
        self, path: str, capacity: int, key_size: int, value_size: int, tag: int = 0
    ) -> None: ...
    @staticmethod
    def open(
        path: str, capacity: int, key_size: int, value_size: int, tag: int = 0
    ) -> BTreeMap: ...
    @property
    def capacity(self) -> int: ...
    @property
    def key_size(self) -> int: ...
    @property
    def value_size(self) -> int: ...
    @property
    def nodes(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: bytes) -> bool: ...
    def insert(self, key: bytes, value: bytes) -> bytes | None: ...
    def insert_many(self, pairs: Sequence[tuple[bytes, bytes]]) -> int: ...
    def get(self, key: bytes) -> bytes | None: ...
    def remove(self, key: bytes) -> bytes | None: ...
    def first(self) -> tuple[bytes, bytes] | None: ...
    def last(self) -> tuple[bytes, bytes] | None: ...
    def clear(self) -> None: ...
    def flush(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class Arena:
    def __init__(self, path: str, capacity_bytes: int) -> None: ...
    @staticmethod
    def open(path: str, capacity_bytes: int) -> Arena: ...
    @staticmethod
    def open_read_only(path: str, capacity_bytes: int) -> Arena: ...
    @property
    def capacity_bytes(self) -> int: ...
    @property
    def used_bytes(self) -> int: ...
    @property
    def remaining_bytes(self) -> int: ...
    @property
    def writable(self) -> bool: ...
    def intern(self, value: str) -> int | None: ...
    def intern_bytes(self, value: bytes) -> int | None: ...
    def intern_many(self, values: Sequence[str]) -> list[int]: ...
    def get(self, reference: int) -> str: ...
    def get_bytes(self, reference: int) -> bytes: ...
    def get_many(self, references: Sequence[int]) -> list[str]: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class LinkedList:
    def __init__(
        self, path: str, capacity: int, element_size: int, alignment: int = 1, tag: int = 0
    ) -> None: ...
    @staticmethod
    def open(
        path: str, capacity: int, element_size: int, alignment: int = 1, tag: int = 0
    ) -> LinkedList: ...
    @property
    def capacity(self) -> int: ...
    @property
    def element_size(self) -> int: ...
    def __len__(self) -> int: ...
    def push_front(self, value: bytes) -> int: ...
    def push_back(self, value: bytes) -> int: ...
    def push_back_many(self, values: Sequence[bytes]) -> list[int]: ...
    def pop_front(self) -> bytes | None: ...
    def pop_back(self) -> bytes | None: ...
    def get(self, index: int) -> bytes: ...
    def remove(self, index: int) -> bytes: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class FrameRegion:
    def __init__(self, path: str, block_size: int, block_count: int) -> None: ...
    @staticmethod
    def open(path: str, block_size: int, block_count: int) -> FrameRegion: ...
    @property
    def block_size(self) -> int: ...
    @property
    def block_count(self) -> int: ...
    def allocate(self) -> int | None: ...
    def free(self, index: int) -> None: ...
    def write_new(self, payload: bytes) -> int | None: ...
    def write_block(self, index: int, payload: bytes) -> None: ...
    def read_block(self, index: int, length: int) -> bytes: ...
    def take_block(self, index: int, length: int) -> bytes: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

# Rings and channels.

class Channel:
    max_item_size: int
    def __init__(
        self, path: str, capacity: int = 1024, senders: int = 1, readers: int = 1
    ) -> None: ...
    @staticmethod
    def open(path: str, capacity: int = 1024) -> Channel: ...
    def send(self, item: bytes) -> bool: ...
    def send_many(self, items: Sequence[bytes]) -> int: ...
    def send_for(self, item: bytes, timeout: float | None = None) -> bool: ...
    def recv(self) -> bytes | None: ...
    def recv_many(self, max_items: int = 256) -> list[bytes]: ...
    def recv_for(self, timeout: float | None = None) -> bytes | None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class KvMap:
    def __init__(
        self, path: str, capacity: int = 1024, readers: int = 1, writers: int = 1
    ) -> None: ...
    def insert(self, key: int, value: int) -> bool: ...
    def insert_many(self, entries: Sequence[tuple[int, int]]) -> list[bool]: ...
    def get(self, key: int) -> int | None: ...
    def get_many(self, keys: Sequence[int]) -> list[int | None]: ...
    def __contains__(self, key: int) -> bool: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class Ring:
    def __init__(
        self,
        path: str,
        capacity: int,
        max_producers: int = 1,
        max_consumers: int = 1,
        stamps: str | None = None,
    ) -> None: ...
    @staticmethod
    def open(
        path: str,
        capacity: int,
        max_producers: int = 1,
        max_consumers: int = 1,
        stamps: str | None = None,
    ) -> Ring: ...
    @property
    def stamped(self) -> bool: ...
    @property
    def stamps(self) -> str | None: ...
    @property
    def shape(self) -> str: ...
    @property
    def capacity(self) -> int: ...
    @property
    def total_capacity(self) -> int: ...
    @property
    def max_producers(self) -> int: ...
    @property
    def max_consumers(self) -> int: ...
    @property
    def approx_len(self) -> int: ...
    @property
    def morph_refusals(self) -> int: ...
    def register_producer(self) -> int: ...
    def register_consumer(self) -> int: ...
    def is_empty(self) -> bool: ...
    def send(self, producer: int, item: bytes) -> bool: ...
    def send_many(self, producer: int, items: Sequence[bytes]) -> int: ...
    def send_buffer(self, producer: int, data: bytes, item_len: int) -> int: ...
    def recv(self, consumer: int) -> bytes | None: ...
    def recv_many(self, consumer: int, max_items: int) -> list[bytes]: ...
    def send_frame(self, producer: int, payload: bytes) -> bool: ...
    def recv_frame(self, consumer: int) -> bytes | None: ...
    def ordered_receiver(self, consumer: int) -> OrderedReceiver: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class OrderedReceiver:
    def drain(self, max_items: int = 4096) -> list[tuple[bytes, int]]: ...
    def recv(self) -> tuple[bytes, int] | None: ...
    def flush(self) -> tuple[bytes, int] | None: ...
    def flush_all(self) -> list[tuple[bytes, int]]: ...
    @property
    def strategy(self) -> str: ...
    @property
    def corrections(self) -> int: ...

class ReorderWindow:
    def __init__(self, floor: int = 8, cap: int = 1024) -> None: ...
    def push(self, stamp: int, payload: bytes) -> None: ...
    def push_many(self, items: Sequence[tuple[int, bytes]]) -> int: ...
    def take(self) -> tuple[bytes, int] | None: ...
    def flush(self) -> tuple[bytes, int] | None: ...
    def flush_all(self) -> list[tuple[bytes, int]]: ...
    def widen_to(self, window: int) -> None: ...
    @property
    def window(self) -> int: ...
    @property
    def corrections(self) -> int: ...
    def __len__(self) -> int: ...

class SpscRing:
    def __init__(self, path: str, capacity: int) -> None: ...
    @staticmethod
    def open(path: str, capacity: int) -> SpscRing: ...
    @property
    def capacity(self) -> int: ...
    @property
    def payload_size(self) -> int: ...
    def push(self, item: bytes) -> bool: ...
    def push_many(self, items: Sequence[bytes]) -> int: ...
    def push_buffer(self, data: bytes, item_len: int) -> int: ...
    def pop(self) -> bytes | None: ...
    def pop_many(self, max_items: int) -> list[bytes]: ...
    def pop_buffer(self, max_items: int) -> tuple[bytes, int]: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class BroadcastRing:
    def __init__(self, path: str, capacity: int) -> None: ...
    @staticmethod
    def open(path: str, capacity: int) -> BroadcastRing: ...
    @property
    def capacity(self) -> int: ...
    @property
    def payload_size(self) -> int: ...
    @property
    def producer_position(self) -> int: ...
    @property
    def active_consumers(self) -> int: ...
    def register_consumer(self) -> int: ...
    def unregister_consumer(self, consumer: int) -> None: ...
    def lag(self, consumer: int) -> int: ...
    def push(self, item: bytes) -> bool: ...
    def push_many(self, items: Sequence[bytes]) -> int: ...
    def recv(self, consumer: int) -> bytes | None: ...
    def recv_many(self, consumer: int, max_items: int) -> list[bytes]: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class CapacityRing:
    def __init__(
        self,
        path: str,
        capacity: int,
        max_producers: int = 1,
        max_consumers: int = 1,
        stamped: bool = False,
    ) -> None: ...
    @staticmethod
    def open(
        path: str,
        capacity: int,
        max_producers: int = 1,
        max_consumers: int = 1,
        stamped: bool = False,
    ) -> CapacityRing: ...
    @property
    def capacity(self) -> int: ...
    @property
    def pin_generation(self) -> int: ...
    def register_producer(self) -> int: ...
    def register_consumer(self) -> int: ...
    def send(self, producer: int, item: bytes) -> bool: ...
    def send_many(self, producer: int, items: Sequence[bytes]) -> int: ...
    def recv(self, consumer: int) -> bytes | None: ...
    def recv_many(self, consumer: int, max_items: int) -> list[bytes]: ...
    def morph_to(self, capacity: int) -> None: ...
    def prewarm(self, capacity: int) -> None: ...
    @property
    def warm_capacity(self) -> int | None: ...
    @property
    def warm_hits(self) -> int: ...
    @property
    def stale_pops(self) -> int: ...
    def clear_warm(self) -> None: ...
    @property
    def stamped(self) -> bool: ...
    @property
    def ordering_mode(self) -> str | None: ...
    def set_ordering_mode(self, mode: str) -> None: ...
    @property
    def inversions(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class LocaleRing:
    def __init__(
        self,
        path: str,
        capacity: int,
        max_producers: int = 1,
        max_consumers: int = 1,
        stamped: bool = False,
    ) -> None: ...
    @staticmethod
    def open(
        path: str,
        capacity: int,
        max_producers: int = 1,
        max_consumers: int = 1,
        stamped: bool = False,
    ) -> LocaleRing: ...
    @property
    def locale(self) -> str: ...
    @property
    def locale_generation(self) -> int: ...
    def register_producer(self) -> int: ...
    def register_consumer(self) -> int: ...
    def send(self, producer: int, item: bytes) -> bool: ...
    def send_many(self, producer: int, items: Sequence[bytes]) -> int: ...
    def recv(self, consumer: int) -> bytes | None: ...
    def recv_many(self, consumer: int, max_items: int) -> list[bytes]: ...
    def migrate_to(self, locale: str) -> None: ...
    @property
    def stamped(self) -> bool: ...
    @property
    def ordering_mode(self) -> str | None: ...
    def set_ordering_mode(self, mode: str) -> None: ...
    @property
    def inversions(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class MpscProducer:
    @property
    def capacity(self) -> int: ...
    @property
    def payload_size(self) -> int: ...
    def push(self, item: bytes) -> bool: ...
    def push_many(self, items: Sequence[bytes]) -> int: ...
    def push_buffer(self, data: bytes, item_len: int) -> int: ...

class MpscConsumer:
    @property
    def producers(self) -> int: ...
    @property
    def approx_len(self) -> int: ...
    def pop(self) -> bytes | None: ...
    def pop_many(self, max_items: int) -> list[bytes]: ...

def mpsc_pool(
    path: str, producers: int, capacity: int
) -> tuple[list[MpscProducer], MpscConsumer]: ...
def mpsc_pool_open(
    path: str, producers: int, capacity: int
) -> tuple[list[MpscProducer], MpscConsumer]: ...

class MpmcProducer:
    @property
    def capacity(self) -> int: ...
    def push(self, item: bytes) -> bool: ...
    def push_many(self, items: Sequence[bytes]) -> int: ...

class MpmcConsumer:
    @property
    def rings(self) -> int: ...
    @property
    def approx_len(self) -> int: ...
    def pop(self) -> bytes | None: ...
    def pop_many(self, max_items: int) -> list[bytes]: ...

def mpmc_grid(
    path: str, producers: int, consumers: int, capacity: int
) -> tuple[list[MpmcProducer], list[MpmcConsumer]]: ...
def mpmc_grid_open(
    path: str, producers: int, consumers: int, capacity: int
) -> tuple[list[MpmcProducer], list[MpmcConsumer]]: ...

class LamportProducer:
    @property
    def capacity(self) -> int: ...
    @property
    def payload_size(self) -> int: ...
    def push(self, item: bytes) -> bool: ...
    def push_many(self, items: Sequence[bytes]) -> int: ...
    def push_buffer(self, data: bytes, item_len: int) -> int: ...

class LamportConsumer:
    @property
    def capacity(self) -> int: ...
    def pop(self) -> bytes | None: ...
    def pop_many(self, max_items: int) -> list[bytes]: ...

def lamport_pair(path: str, capacity: int) -> tuple[LamportProducer, LamportConsumer]: ...
def lamport_pair_open(
    path: str, capacity: int
) -> tuple[LamportProducer, LamportConsumer]: ...

class PubSub:
    def __init__(self, path: str, capacity: int) -> None: ...
    @staticmethod
    def open(path: str, capacity: int) -> PubSub: ...
    @property
    def capacity(self) -> int: ...
    @property
    def head(self) -> int: ...
    @property
    def payload_size(self) -> int: ...
    def publish(self, item: bytes) -> int: ...
    def publish_many(self, items: Sequence[bytes]) -> int | None: ...
    def read_at(self, position: int) -> bytes | None: ...
    def subscribe(self) -> Subscriber: ...
    def subscribe_from(self, position: int) -> Subscriber: ...

class Subscriber:
    @property
    def position(self) -> int: ...
    def lag(self) -> int: ...
    def next(self) -> bytes | None: ...
    def next_many(self, max_items: int) -> list[bytes]: ...

class Stack:
    def __init__(
        self, path: str, capacity: int, element_size: int, alignment: int = 1, tag: int = 0
    ) -> None: ...
    @staticmethod
    def open(
        path: str, capacity: int, element_size: int, alignment: int = 1, tag: int = 0
    ) -> Stack: ...
    @property
    def capacity(self) -> int: ...
    @property
    def element_size(self) -> int: ...
    @property
    def approx_len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def push(self, item: bytes) -> bool: ...
    def push_many(self, items: Sequence[bytes]) -> int: ...
    def pop(self) -> bytes | None: ...
    def pop_many(self, max_items: int) -> list[bytes]: ...
    def peek(self) -> bytes | None: ...
    def flush(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class Deque:
    def __init__(
        self, path: str, capacity: int, element_size: int, alignment: int = 1, tag: int = 0
    ) -> None: ...
    @staticmethod
    def open_as_thief(
        path: str, element_size: int, alignment: int = 1, tag: int = 0
    ) -> Deque: ...
    @property
    def capacity(self) -> int: ...
    @property
    def element_size(self) -> int: ...
    @property
    def approx_len(self) -> int: ...
    def push(self, item: bytes) -> bool: ...
    def push_many(self, items: Sequence[bytes]) -> int: ...
    def pop(self) -> bytes | None: ...
    def steal(self) -> bytes | None: ...
    def steal_many(self, max_items: int) -> list[bytes]: ...
    def flush(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

# Coordination.

class RWLock:
    def __init__(self, path: str) -> None: ...
    @staticmethod
    def open(path: str) -> RWLock: ...
    @property
    def readers(self) -> int: ...
    def read(self) -> Hold: ...
    def read_for(self, timeout: float) -> Hold | None: ...
    def write_for(self, timeout: float) -> Hold | None: ...
    def try_read(self) -> Hold | None: ...
    def write(self) -> Hold: ...
    def try_write(self) -> Hold | None: ...

class Hold:
    @property
    def held(self) -> bool: ...
    def release(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class Reservoir:
    max_value_bytes: int
    def __init__(self, path: str, capacity: int) -> None: ...
    @staticmethod
    def open(path: str, capacity: int) -> Reservoir: ...
    def record(self, value: bytes) -> int | None: ...
    def record_many(self, values: Sequence[bytes]) -> int: ...
    def snapshot(self) -> list[bytes]: ...
    @property
    def total_seen(self) -> int: ...
    @property
    def capacity(self) -> int: ...
    def reset(self) -> None: ...
    def flush(self) -> None: ...
    def flush_async(self) -> None: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class BlockedBloomFilter:
    def __init__(self, path: str, bits: int, hashes: int) -> None: ...
    @staticmethod
    def open(path: str, bits: int, hashes: int) -> BlockedBloomFilter: ...
    @staticmethod
    def reset(path: str, bits: int, hashes: int) -> BlockedBloomFilter: ...
    @staticmethod
    def suggest(items: int, false_positive_rate: float) -> tuple[int, int]: ...
    def insert(self, item: bytes) -> None: ...
    def insert_many(self, items: Sequence[bytes]) -> int: ...
    def contains(self, item: bytes) -> bool: ...
    def contains_many(self, items: Sequence[bytes]) -> list[bool]: ...
    def clear(self) -> None: ...
    @property
    def hashes(self) -> int: ...
    @property
    def blocks(self) -> int: ...
    def flush(self) -> None: ...
    def __contains__(self, item: bytes) -> bool: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class HandleTable:
    max_value_bytes: int
    def __init__(self, path: str, capacity: int) -> None: ...
    @staticmethod
    def open(path: str, capacity: int) -> HandleTable: ...
    @staticmethod
    def reset(path: str, capacity: int) -> HandleTable: ...
    def insert(self, value: bytes) -> int: ...
    def insert_many(self, values: Sequence[bytes]) -> list[int]: ...
    def get(self, handle: int) -> bytes | None: ...
    def get_many(self, handles: Sequence[int]) -> list[bytes | None]: ...
    def contains(self, handle: int) -> bool: ...
    def remove(self, handle: int) -> bytes | None: ...
    @property
    def capacity(self) -> int: ...
    def flush(self) -> None: ...
    def flush_async(self) -> None: ...
    def __contains__(self, handle: int) -> bool: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class TimePointTile:
    lanes: int
    max_value_bytes: int
    def __init__(self, path: str) -> None: ...
    @staticmethod
    def open(path: str) -> TimePointTile: ...
    @staticmethod
    def reset(path: str) -> TimePointTile: ...
    def insert(self, version: int, value: bytes) -> int: ...
    def remove(self, lane: int) -> None: ...
    def at(self, lane: int) -> tuple[int, bytes] | None: ...
    def visible_mask(self, version: int) -> int: ...
    def visible_count(self, version: int) -> int: ...
    def visible(self, version: int) -> list[tuple[int, bytes]]: ...
    @property
    def full(self) -> bool: ...
    def flush(self) -> None: ...
    def flush_async(self) -> None: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class VersionChain:
    max_value_bytes: int
    def __init__(self, path: str, capacity: int) -> None: ...
    @staticmethod
    def open(path: str, capacity: int) -> VersionChain: ...
    @staticmethod
    def reset(path: str, capacity: int) -> VersionChain: ...
    def push(self, version: int, value: bytes) -> None: ...
    def read_at(self, version: int) -> bytes | None: ...
    @property
    def current(self) -> tuple[int, bytes] | None: ...
    def clear(self) -> None: ...
    @property
    def capacity(self) -> int: ...
    def flush(self) -> None: ...
    def flush_async(self) -> None: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class VersionedSlab:
    depth: int
    max_value_bytes: int
    def __init__(
        self, path: str, capacity: int, epochs_path: str, max_pins: int = 16
    ) -> None: ...
    @staticmethod
    def open(
        path: str, capacity: int, epochs_path: str, max_pins: int = 16
    ) -> VersionedSlab: ...
    def set(self, slot: int, value: bytes) -> None: ...
    def set_at(self, slot: int, value: bytes, born: int) -> None: ...
    def get(self, slot: int) -> bytes | None: ...
    def history(self, slot: int) -> list[tuple[bytes, int, int | None]]: ...
    def retire(self, slot: int) -> bytes | None: ...
    def retire_at(self, slot: int, died: int) -> bytes | None: ...
    def pin(self) -> SlabPin: ...
    def sweep_slot(self, slot: int) -> int: ...
    def void_epoch(self, epoch: int) -> int: ...
    @property
    def capacity(self) -> int: ...
    def flush(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class SlabPin:
    @property
    def epoch(self) -> int: ...
    @property
    def held(self) -> bool: ...
    def get(self, slot: int) -> bytes | None: ...
    def get_many(self, slots: Sequence[int]) -> list[bytes | None]: ...
    def release(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class VersionedMap:
    def __init__(
        self, path: str, capacity: int, epochs_path: str, max_pins: int = 16
    ) -> None: ...
    @staticmethod
    def open(
        path: str, capacity: int, epochs_path: str, max_pins: int = 16
    ) -> VersionedMap: ...
    def insert(self, key: int, value: int) -> int | None: ...
    def insert_at(self, key: int, value: int, born: int) -> int | None: ...
    def insert_many(self, entries: Sequence[tuple[int, int]]) -> list[int | None]: ...
    def get(self, key: int) -> int | None: ...
    def get_many(self, keys: Sequence[int]) -> list[int | None]: ...
    def remove(self, key: int) -> int | None: ...
    def remove_at(self, key: int, died: int) -> int | None: ...
    def pin(self) -> MapPin: ...
    def sweep(self) -> int: ...
    def void_epoch(self, epoch: int) -> int: ...
    @property
    def capacity(self) -> int: ...
    def flush(self) -> None: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class MapPin:
    @property
    def epoch(self) -> int: ...
    @property
    def held(self) -> bool: ...
    def get(self, key: int) -> int | None: ...
    def get_many(self, keys: Sequence[int]) -> list[int | None]: ...
    def scan(
        self, low: int | None = None, high: int | None = None, limit: int = 1024
    ) -> list[tuple[int, int]]: ...
    def scan_from(
        self, low: int | None = None, high: int | None = None, limit: int = 1024
    ) -> tuple[list[tuple[int, int]], int | None]: ...
    def release(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class LanedMap:
    def __init__(
        self,
        directory: str,
        lanes: int = 4,
        nodes_per_lane: int = 256,
        max_pins: int = 16,
    ) -> None: ...
    @staticmethod
    def open(
        directory: str,
        lanes: int = 4,
        nodes_per_lane: int = 256,
        max_pins: int = 16,
    ) -> LanedMap: ...
    def claim_lane(self) -> LaneClaim: ...
    def claim_lane_for(self, key: int) -> LaneClaim: ...
    def lane_of(self, key: int) -> int | None: ...
    def get(self, key: int) -> int | None: ...
    def get_many(self, keys: Sequence[int]) -> list[int | None]: ...
    def pin(self) -> LanedPin: ...
    @property
    def held_lanes(self) -> int: ...
    def reap_dead_claims(self) -> int: ...
    def sweep(self) -> int: ...
    def void_epoch(self, epoch: int) -> int: ...
    @property
    def lanes(self) -> int: ...
    def flush(self) -> None: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class LaneClaim:
    @property
    def index(self) -> int: ...
    @property
    def held(self) -> bool: ...
    def insert(self, key: int, value: int) -> int | None: ...
    def insert_at(self, key: int, value: int, born: int) -> int | None: ...
    def insert_many(self, entries: Sequence[tuple[int, int]]) -> list[int | None]: ...
    def remove(self, key: int) -> int | None: ...
    def remove_at(self, key: int, died: int) -> int | None: ...
    def release(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class LanedPin:
    @property
    def epoch(self) -> int: ...
    @property
    def held(self) -> bool: ...
    def get(self, key: int) -> int | None: ...
    def get_many(self, keys: Sequence[int]) -> list[int | None]: ...
    def scan(
        self, low: int | None = None, high: int | None = None, limit: int = 1024
    ) -> list[tuple[int, int]]: ...
    def scan_from(
        self, low: int | None = None, high: int | None = None, limit: int = 1024
    ) -> tuple[list[tuple[int, int]], int | None]: ...
    def release(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class TopologyMap:
    def __init__(
        self,
        path: str,
        participants: int,
        fan_out_threshold: int | None = None,
        fan_in_threshold: int | None = None,
    ) -> None: ...
    @staticmethod
    def open(path: str, participants: int) -> TopologyMap: ...
    @staticmethod
    def reset(
        path: str,
        participants: int,
        fan_out_threshold: int | None = None,
        fan_in_threshold: int | None = None,
    ) -> TopologyMap: ...
    def record_send(self, sender: int, receiver: int) -> int: ...
    def record_many(self, sends: Sequence[tuple[int, int]]) -> int: ...
    def fan_out(self, sender: int) -> int: ...
    def fan_in(self, receiver: int) -> int: ...
    @property
    def busiest_sender(self) -> tuple[int, int]: ...
    @property
    def busiest_receiver(self) -> tuple[int, int]: ...
    def recommend(self) -> str: ...
    def publish_recommendation(self) -> str: ...
    def published_recommendation(self) -> str: ...
    @property
    def broadcast_root(self) -> int: ...
    @property
    def recommendation_epoch(self) -> int: ...
    @property
    def total_sends(self) -> int: ...
    @property
    def participants(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class Graph:
    def __init__(self, path: str, max_nodes: int, max_edges: int) -> None: ...
    @staticmethod
    def open(path: str, max_nodes: int, max_edges: int) -> Graph: ...
    def add_node(self, value: int) -> int: ...
    def add_nodes(self, values: Sequence[int]) -> list[int]: ...
    def add_edge(self, source: int, target: int, value: int) -> int: ...
    def add_edges(self, edges: Sequence[tuple[int, int, int]]) -> list[int]: ...
    def node_value(self, node: int) -> int | None: ...
    def neighbors(self, source: int) -> list[tuple[int, int, int]]: ...
    def out_degree(self, source: int) -> int | None: ...
    def remove_edge(self, source: int, edge: int) -> int | None: ...
    @property
    def node_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def max_nodes(self) -> int: ...
    @property
    def max_edges(self) -> int: ...
    def flush(self) -> None: ...
    def flush_async(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class Universal:
    def __init__(self, path: str, capacity: int) -> None: ...
    @staticmethod
    def open(path: str, capacity: int) -> Universal: ...
    @staticmethod
    def reset(path: str, capacity: int) -> Universal: ...
    def insert(self, value: int) -> None: ...
    def insert_many(self, values: Sequence[int]) -> int: ...
    def contains(self, value: int) -> bool: ...
    def contains_many(self, values: Sequence[int]) -> list[bool]: ...
    def snapshot(self) -> list[int]: ...
    def clear(self) -> None: ...
    @property
    def strategy(self) -> str: ...
    @property
    def migrations(self) -> int: ...
    @property
    def generation(self) -> int: ...
    def migrate_to(self, strategy: str) -> None: ...
    @property
    def op_counts(self) -> tuple[int, int]: ...
    def __contains__(self, value: int) -> bool: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class Tower:
    def __init__(
        self,
        path: str,
        capacity: int,
        value_size: int,
        levels: Sequence[tuple[str, int]],
    ) -> None: ...
    @staticmethod
    def open(
        path: str,
        capacity: int,
        value_size: int,
        levels: Sequence[tuple[str, int]],
    ) -> Tower: ...
    def append(self, value: bytes) -> list[int]: ...
    def append_many(self, values: Sequence[bytes]) -> list[list[int]]: ...
    def insert_at_top(self, top: int, value: bytes) -> list[int]: ...
    def get(self, path: Sequence[int]) -> bytes: ...
    def get_many(self, paths: Sequence[Sequence[int]]) -> list[bytes]: ...
    @property
    def depth(self) -> int: ...
    @property
    def value_size(self) -> int: ...
    def flush(self) -> None: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class QosPolicy:
    def __init__(
        self,
        durability: str = "volatile",
        reliability: str = "best_effort",
        keep_last: int | None = 1024,
        max_latency: float = 0.1,
    ) -> None: ...
    @staticmethod
    def streaming() -> QosPolicy: ...
    @staticmethod
    def reliable_pubsub() -> QosPolicy: ...
    @staticmethod
    def persistent_log() -> QosPolicy: ...
    durability: str
    reliability: str
    keep_last: int | None
    max_latency: float
    ordering: str
    def snapshot(self) -> QosSnapshot: ...

class QosSnapshot:
    @property
    def durability(self) -> str: ...
    @property
    def reliability(self) -> str: ...
    @property
    def keep_last(self) -> int | None: ...
    @property
    def max_latency(self) -> float: ...
    @property
    def ordering(self) -> str: ...
    def recommends_locale_change(self, current: str) -> str | None: ...
    def recommends_ordering_change(self, current: str) -> str | None: ...

class SensSender:
    def __init__(
        self,
        local: tuple[str, int],
        peer: tuple[str, int],
        max_item_size: int,
        code: str | None = None,
    ) -> None: ...
    def send(self, item: bytes) -> None: ...
    def send_many(self, items: Sequence[bytes]) -> int: ...
    @property
    def max_item_size(self) -> int: ...
    @property
    def local_addr(self) -> tuple[str, int]: ...
    @property
    def code(self) -> str: ...
    @property
    def switches(self) -> int: ...
    @property
    def loss(self) -> float | None: ...
    @property
    def datagrams(self) -> tuple[int, int]: ...

class SensReceiver:
    def __init__(
        self, local: tuple[str, int], max_item_size: int, code: str | None = None
    ) -> None: ...
    def poll(self) -> list[bytes]: ...
    def poll_from(self) -> list[tuple[int, bytes]]: ...
    @property
    def max_item_size(self) -> int: ...
    @property
    def local_addr(self) -> tuple[str, int]: ...
    @property
    def code(self) -> str: ...
    @property
    def switches(self) -> int: ...
    @property
    def send_failures(self) -> int: ...
    @property
    def alive(self) -> bool: ...

# Present only in a wheel built with the tcp-bridge feature. Check
# "tcp" in subetha.transports before reaching for these.

class TcpBridgeClient:
    def __init__(self, ring: Ring, server: tuple[str, int]) -> None: ...
    def run(self, items: int) -> None: ...

class TcpBridgeServer:
    def __init__(self, ring: Ring, local: tuple[str, int]) -> None: ...
    @property
    def local_addr(self) -> tuple[str, int]: ...
    def accept_one(self) -> int: ...

# Present only in a wheel built with the quic-bridge feature.

def generate_self_signed_cert(name: str) -> tuple[bytes, bytes]: ...

class QuicBridgeClient:
    def __init__(
        self,
        ring: Ring,
        server: tuple[str, int],
        cert: bytes,
        server_name: str,
        local: tuple[str, int] | None = None,
    ) -> None: ...
    def run(self, items: int) -> None: ...

class QuicBridgeServer:
    def __init__(
        self, ring: Ring, local: tuple[str, int], cert: bytes, key: bytes
    ) -> None: ...
    @property
    def local_addr(self) -> tuple[str, int]: ...
    def accept_one(self) -> int: ...

class OwnerLease:
    max_value_bytes: int
    def __init__(self, path: str, value: bytes | None = None) -> None: ...
    @staticmethod
    def open(path: str) -> OwnerLease: ...
    @staticmethod
    def reset(path: str, value: bytes | None = None) -> OwnerLease: ...
    def try_acquire(self, grace_epochs: int = 0, pid: int | None = None) -> bool: ...
    def release(self, pid: int | None = None) -> bool: ...
    def hold(self, grace_epochs: int = 0, pid: int | None = None) -> LeaseHold: ...
    def read(self, pid: int | None = None) -> bytes | None: ...
    def write(self, value: bytes, pid: int | None = None) -> bool: ...
    def beat(self, pid: int | None = None) -> bool: ...
    def tick_epoch(self) -> int: ...
    @property
    def owner(self) -> int | None: ...
    def held_by_me(self, pid: int | None = None) -> bool: ...
    @property
    def term(self) -> int: ...
    def flush(self) -> None: ...
    def flush_async(self) -> None: ...

class LeaseHold:
    @property
    def held(self) -> bool: ...
    def read(self) -> bytes | None: ...
    def write(self, value: bytes) -> bool: ...
    def beat(self) -> bool: ...
    def release(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class Semaphore:
    def __init__(self, path: str, initial: int, max_permits: int | None = None) -> None: ...
    @staticmethod
    def open(path: str, max_permits: int) -> Semaphore: ...
    @property
    def available(self) -> int: ...
    @property
    def waiters(self) -> int: ...
    @property
    def max_permits(self) -> int: ...
    def acquire(self) -> PermitHold: ...
    def acquire_for(self, timeout: float) -> PermitHold | None: ...
    def try_acquire(self) -> PermitHold | None: ...

class PermitHold:
    @property
    def held(self) -> bool: ...
    def release(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class Condvar:
    def __init__(self, path: str) -> None: ...
    @staticmethod
    def open(path: str) -> Condvar: ...
    @property
    def generation(self) -> int: ...
    def wait_for(
        self, predicate: Callable[[], object], timeout: float | None = None
    ) -> bool: ...
    def notify_one(self) -> int: ...
    def notify_all(self) -> int: ...

class LazyValue:
    def __init__(self, path: str, value_bytes: int) -> None: ...
    @staticmethod
    def open(path: str, value_bytes: int) -> LazyValue: ...
    @property
    def value_size(self) -> int: ...
    @property
    def ready(self) -> bool: ...
    def get(self) -> bytes | None: ...
    def claim(self, pid: int | None = None) -> bool: ...
    def publish(self, value: bytes, pid: int | None = None) -> bool: ...
    def wait(self, timeout: float = 30.0) -> bytes: ...

class Heartbeat:
    def __init__(self, path: str, capacity: int) -> None: ...
    @staticmethod
    def open(path: str, capacity: int) -> Heartbeat: ...
    @property
    def capacity(self) -> int: ...
    @property
    def global_epoch(self) -> int: ...
    def register(self, pid: int | None = None) -> int: ...
    def unregister(self, slot: int) -> None: ...
    def beat(self, slot: int) -> None: ...
    def tick_global_epoch(self) -> int: ...
    def snapshot(self, slot: int) -> dict[str, int] | None: ...

class EpochBarrier:
    def __init__(self, path: str, heartbeat: Heartbeat, grace_epochs: int = 3) -> None: ...
    @staticmethod
    def open(path: str, heartbeat: Heartbeat, grace_epochs: int = 3) -> EpochBarrier: ...
    @property
    def live_peers(self) -> int: ...
    @property
    def current_epoch(self) -> int: ...
    @property
    def arrived(self) -> int: ...
    def snapshot(self) -> tuple[int, int]: ...
    def wait(
        self, epoch: int, timeout: float | None = None, quorum: int | None = None
    ) -> bool: ...

class Epochs:
    def __init__(self, path: str, capacity: int) -> None: ...
    @staticmethod
    def open(path: str, capacity: int) -> Epochs: ...
    @property
    def capacity(self) -> int: ...
    @property
    def now(self) -> int: ...
    @property
    def open_tickets(self) -> int: ...
    def advance(self) -> int: ...
    def claim_ticket(self) -> tuple[int, int]: ...
    def publish_ticket(self, slot: int) -> None: ...
    def dead_tickets(self) -> list[int]: ...
    def free_dead_ticket(self, epoch: int) -> bool: ...

class LeaderElection:
    def __init__(self, path: str) -> None: ...
    @staticmethod
    def open(path: str) -> LeaderElection: ...
    @property
    def leader(self) -> int | None: ...
    @property
    def term(self) -> int: ...
    @property
    def global_epoch(self) -> int: ...
    def try_claim(self, pid: int | None = None, grace_epochs: int = 3) -> bool: ...
    def beat(self, pid: int | None = None) -> bool: ...
    def step_down(self, pid: int | None = None) -> bool: ...
    def am_i_leader(self, pid: int | None = None) -> bool: ...
    def tick_epoch(self) -> int: ...

class HolderTable:
    def __init__(self, path: str, capacity: int) -> None: ...
    @staticmethod
    def open(path: str, capacity: int) -> HolderTable: ...
    @property
    def capacity(self) -> int: ...
    @property
    def live(self) -> int: ...
    def claim(self, payload: int) -> int | None: ...
    def reserve(self) -> int | None: ...
    def publish(self, slot: int, payload: int) -> None: ...
    def payload(self, slot: int) -> int | None: ...
    def release(self, slot: int) -> None: ...

class FenceClock:
    def __init__(self, path: str, capacity: int) -> None: ...
    @staticmethod
    def open(path: str, capacity: int) -> FenceClock: ...
    @property
    def capacity(self) -> int: ...
    @property
    def shared_clock_us(self) -> int: ...
    def register(self, pid: int | None = None) -> int: ...
    def unregister(self, slot: int) -> None: ...
    def tick(self, slot: int) -> tuple[int, int]: ...
    def merge(self, slot: int, physical_us: int, logical: int) -> tuple[int, int]: ...
    def get_local(self, slot: int) -> tuple[int, int]: ...
    def global_fence(self) -> tuple[int, int]: ...

class SharedArc:
    def __init__(
        self, path: str, value: bytes, max_holders: int = 16, keep_on_last: bool = False
    ) -> None: ...
    @staticmethod
    def open(
        path: str, value_bytes: int, max_holders: int = 16, keep_on_last: bool = False
    ) -> SharedArc: ...
    @property
    def holders(self) -> int: ...
    @property
    def value_size(self) -> int: ...
    def get(self) -> bytes: ...
    def read_at(self, offset: int, length: int) -> bytes: ...
    def write_at(self, offset: int, value: bytes) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class NotifierSet:
    def __init__(self, path: str) -> None: ...
    @property
    def attached(self) -> int: ...
    def signal(self) -> int: ...
    def attach(self) -> Notifier: ...

class Notifier:
    @property
    def index(self) -> int: ...
    @property
    def native(self) -> int: ...
    @property
    def is_signaled(self) -> bool: ...
    def wait(self, timeout: float | None = None) -> bool: ...
    def drain(self) -> None: ...

# Probabilistic and specialist structures.

class BloomFilter:
    def __init__(self, path: str, n_bits: int, n_hashes: int) -> None: ...
    @staticmethod
    def open(path: str, n_bits: int, n_hashes: int) -> BloomFilter: ...
    @staticmethod
    def suggest_config(n_items: int, false_positive_rate: float) -> tuple[int, int]: ...
    @property
    def n_bits(self) -> int: ...
    @property
    def n_hashes(self) -> int: ...
    @property
    def false_positive_rate(self) -> float: ...
    def insert(self, item: bytes) -> None: ...
    def insert_many(self, items: Sequence[bytes]) -> None: ...
    def contains(self, item: bytes) -> bool: ...
    def contains_many(self, items: Sequence[bytes]) -> list[bool]: ...
    def __contains__(self, item: bytes) -> bool: ...
    def clear(self) -> None: ...

class CountMinSketch:
    def __init__(self, path: str, depth: int, width: int) -> None: ...
    @staticmethod
    def open(path: str, depth: int, width: int) -> CountMinSketch: ...
    @staticmethod
    def suggest_config(epsilon: float, delta: float) -> tuple[int, int]: ...
    @property
    def depth(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def total_inserts(self) -> int: ...
    def insert(self, item: bytes) -> None: ...
    def insert_n(self, item: bytes, count: int) -> None: ...
    def insert_many(self, items: Sequence[bytes]) -> int: ...
    def estimate_count(self, item: bytes) -> int: ...
    def estimate_many(self, items: Sequence[bytes]) -> list[int]: ...
    def reset(self) -> None: ...

class HyperLogLog:
    def __init__(self, path: str, precision: int = 14) -> None: ...
    @staticmethod
    def open(path: str, precision: int = 14) -> HyperLogLog: ...
    @property
    def precision(self) -> int: ...
    @property
    def n_registers(self) -> int: ...
    def insert(self, item: bytes) -> None: ...
    def insert_many(self, items: Sequence[bytes]) -> int: ...
    def estimate(self) -> int: ...
    def reset(self) -> None: ...
    def flush(self) -> None: ...

class Histogram:
    def __init__(self, path: str, boundaries: Sequence[int]) -> None: ...
    @staticmethod
    def open(path: str, boundaries: Sequence[int]) -> Histogram: ...
    @property
    def n_buckets(self) -> int: ...
    @property
    def total_count(self) -> int: ...
    @property
    def boundaries(self) -> list[int]: ...
    @property
    def counts(self) -> list[int]: ...
    def record(self, value: int) -> int: ...
    def record_many(self, values: Sequence[int]) -> int: ...
    def count(self, bucket: int) -> int: ...
    def percentile(self, p: float) -> int: ...

class RateLimiter:
    def __init__(self, path: str, capacity: int, refill_per_second: int) -> None: ...
    @staticmethod
    def open(path: str, capacity: int, refill_per_second: int) -> RateLimiter: ...
    @property
    def capacity(self) -> int: ...
    @property
    def refill_per_second(self) -> int: ...
    @property
    def available(self) -> int: ...
    def try_acquire(self, n: int = 1) -> bool: ...
    def reset(self) -> None: ...
    def flush(self) -> None: ...

class LruCache:
    def __init__(self, path: str, capacity: int, key_size: int, value_size: int) -> None: ...
    @staticmethod
    def open(path: str, capacity: int, key_size: int, value_size: int) -> LruCache: ...
    @property
    def capacity(self) -> int: ...
    @property
    def key_size(self) -> int: ...
    @property
    def value_size(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: bytes) -> bool: ...
    def get(self, key: bytes) -> bytes | None: ...
    def get_and_touch(self, key: bytes) -> bytes | None: ...
    def get_many(self, keys: Sequence[bytes]) -> list[bytes | None]: ...
    def touch(self, key: bytes) -> bool: ...
    def put(self, key: bytes, value: bytes) -> bool: ...
    def put_many(self, pairs: Sequence[tuple[bytes, bytes]]) -> int: ...
    def remove(self, key: bytes) -> bytes | None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> bool: ...

class BitVec:
    def __init__(self, path: str, capacity_bits: int) -> None: ...
    @staticmethod
    def open(path: str, capacity_bits: int) -> BitVec: ...
    @property
    def capacity_bits(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> bool: ...
    def get(self, index: int) -> bool: ...
    def set(self, index: int) -> bool: ...
    def clear(self, index: int) -> bool: ...
    def toggle(self, index: int) -> bool: ...
    def set_range(self, lo: int, hi: int) -> None: ...
