//! The C implementation of section 5 against the frozen RS vectors.
//!
//! `crates/subetha-cxc/vectors/rs.txt` is generated by the first
//! implementation and compared against it by a test there. Here it is
//! read as somebody else's output, and every number in it is checked
//! against C written from SENS_O_MATIC_WIRE.md alone.
//!
//! Each geometry withholds exactly `r` shards, which is the most a
//! `(k, r)` code can carry and therefore the case that fails first if
//! the matrix or its inversion is wrong. The file says so itself, and
//! it is the reason these vectors are worth more than a round trip.

use std::path::PathBuf;

use subetha_spec_c::rs;

fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("subetha-cxc")
        .join("vectors")
        .join("rs.txt")
}

/// The vectors' stated source rule, from the file's own header:
///
///     (i * 131 + b * 17 + 7) & 0xff
fn data_shard(index: usize, shard_len: usize) -> Vec<u8> {
    (0..shard_len)
        .map(|b| (index * 131 + b * 17 + 7) as u8)
        .collect()
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn hex_byte(token: &str) -> u8 {
    match u8::from_str_radix(token, 16) {
        Ok(b) => b,
        Err(e) => panic!("{token:?} in the vectors is not a hex byte: {e}"),
    }
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len()).step_by(2).map(|i| hex_byte(&s[i..i + 2])).collect()
}

fn required(line: &str, key: &str) -> usize {
    let Some(raw) = line
        .split_whitespace()
        .find_map(|t| t.strip_prefix(key).and_then(|r| r.strip_prefix('=')))
    else {
        panic!("the vectors line {line:?} names no {key}");
    };
    match raw.parse() {
        Ok(v) => v,
        Err(e) => panic!("{key}={raw} in the vectors is not a number: {e}"),
    }
}

/// The index a labeled row carries, as in `cauchy row  3:` or
/// `parity 11:`.
fn row_index(label: &str) -> usize {
    let Some(token) = label.split_whitespace().last() else {
        panic!("the row label {label:?} is empty");
    };
    match token.parse() {
        Ok(n) => n,
        Err(e) => panic!("the row label {label:?} ends in no number: {e}"),
    }
}

struct Code {
    name: String,
    k: usize,
    r: usize,
    shard_len: usize,
    cauchy: Vec<Vec<u8>>,
    parity: Vec<Vec<u8>>,
    lost: Vec<usize>,
}

fn parse(text: &str) -> Vec<Code> {
    let mut codes: Vec<Code> = Vec::new();
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        if let Some(rest) = line.strip_prefix('[') {
            let Some(close) = rest.find(']') else {
                panic!("the section line {line:?} does not close its name");
            };
            let head = &rest[..close];
            let Some(name) = head.split_whitespace().nth(1) else {
                panic!("the section head {head:?} names no code");
            };
            codes.push(Code {
                name: name.to_string(),
                k: required(line, "k"),
                r: required(line, "r"),
                shard_len: required(line, "shard_len"),
                cauchy: Vec::new(),
                parity: Vec::new(),
                lost: Vec::new(),
            });
            continue;
        }

        let Some(code) = codes.last_mut() else {
            panic!("a line arrived before any code: {line:?}");
        };
        let Some((label, rest)) = line.split_once(':') else {
            panic!("the vectors line {line:?} carries no label");
        };

        if label.starts_with("cauchy row") {
            let at = row_index(label);
            if code.cauchy.len() <= at {
                code.cauchy.resize(at + 1, Vec::new());
            }
            code.cauchy[at] = rest.split_whitespace().map(hex_byte).collect();
        } else if label.starts_with("parity") {
            let at = row_index(label);
            if code.parity.len() <= at {
                code.parity.resize(at + 1, Vec::new());
            }
            code.parity[at] = unhex(rest.trim());
        } else if label.starts_with("lost") {
            let mut lost = Vec::new();
            for token in rest.split_whitespace() {
                match token.parse() {
                    Ok(n) => lost.push(n),
                    Err(e) => panic!("the lost index {token:?} is not a number: {e}"),
                }
            }
            code.lost = lost;
        }
        // The `recovered:` line states a rule in prose rather than data,
        // and the rule it states is the source rule already applied
        // above, so there is nothing further to read from it.
    }
    codes
}

fn load() -> Vec<Code> {
    let path = vectors_path();
    let text = match std::fs::read_to_string(&path) {
        Ok(t) => t,
        Err(e) => panic!("the vectors at {} could not be read: {e}", path.display()),
    };
    parse(&text)
}

/// Section 5.2: `C[j][c] = inverse((k + j) XOR c)`, every entry.
#[test]
fn every_cauchy_entry_matches() {
    let codes = load();
    assert!(!codes.is_empty(), "the vectors carry at least one code");

    let mut checked = 0usize;
    for code in &codes {
        assert_eq!(code.cauchy.len(), code.r, "{}: one row per parity", code.name);
        for (j, row) in code.cauchy.iter().enumerate() {
            assert_eq!(row.len(), code.k, "{}: one column per data shard", code.name);
            for (c, expected) in row.iter().enumerate() {
                assert_eq!(
                    rs::cauchy(code.k, j, c),
                    *expected,
                    "{}: C[{j}][{c}] of a ({}, {}) code",
                    code.name,
                    code.k,
                    code.r
                );
                checked += 1;
            }
        }
    }
    assert!(checked >= 300, "only {checked} entries checked");
}

/// Section 5.2: parity shard `j` is the sum over `c` of `C[j][c]` times
/// data shard `c`.
#[test]
fn every_parity_shard_matches() {
    let codes = load();
    for code in &codes {
        let data: Vec<Vec<u8>> = (0..code.k).map(|i| data_shard(i, code.shard_len)).collect();
        assert_eq!(code.parity.len(), code.r, "{}: one shard per parity", code.name);
        for (j, expected) in code.parity.iter().enumerate() {
            let Some(got) = rs::parity(&data, code.k, j) else {
                panic!("{}: a ({}, {}) code was refused", code.name, code.k, code.r);
            };
            assert_eq!(
                hex(&got),
                hex(expected),
                "{}: parity {j} of a ({}, {}) code",
                code.name,
                code.k,
                code.r
            );
        }
    }
}

/// Section 5.2: any `k` of the `k + r` shards reconstruct the block.
///
/// Every pattern here withholds exactly `r`, the most the code can
/// carry, so a matrix or an inversion that is wrong fails here first.
#[test]
fn every_erasure_pattern_recovers() {
    let codes = load();
    for code in &codes {
        assert_eq!(
            code.lost.len(),
            code.r,
            "{}: the pattern withholds exactly r",
            code.name
        );

        let mut present: Vec<Option<Vec<u8>>> = Vec::with_capacity(code.k + code.r);
        for i in 0..code.k {
            present.push(Some(data_shard(i, code.shard_len)));
        }
        for j in 0..code.r {
            present.push(Some(code.parity[j].clone()));
        }
        for lost in &code.lost {
            assert!(
                *lost < code.k + code.r,
                "{}: shard {lost} is outside the block",
                code.name
            );
            present[*lost] = None;
        }

        let Some(rebuilt) = rs::recover(&present, code.k, code.r) else {
            panic!(
                "{}: a ({}, {}) code with exactly r lost did not recover",
                code.name, code.k, code.r
            );
        };
        assert_eq!(rebuilt.len(), code.k, "{}: k data shards come back", code.name);
        for (i, shard) in rebuilt.iter().enumerate() {
            assert_eq!(
                hex(shard),
                hex(&data_shard(i, code.shard_len)),
                "{}: data shard {i} came back wrong",
                code.name
            );
        }
    }
}

/// Section 5.2: one more than `r` lost is one too many, and the code
/// says so rather than answering plausible bytes.
#[test]
fn past_the_redundancy_is_refused() {
    let codes = load();
    for code in &codes {
        if code.k < 2 {
            // With one data shard there is no "r + 1 lost" that still
            // leaves a block to talk about.
            continue;
        }
        let mut present: Vec<Option<Vec<u8>>> = Vec::with_capacity(code.k + code.r);
        for i in 0..code.k {
            present.push(Some(data_shard(i, code.shard_len)));
        }
        for j in 0..code.r {
            present.push(Some(code.parity[j].clone()));
        }
        for lost in code.lost.iter().take(code.r) {
            present[*lost] = None;
        }
        // One beyond what the code carries: take out any shard still
        // present.
        let Some(extra) = present.iter().position(Option::is_some) else {
            panic!("{}: every shard was already withheld", code.name);
        };
        present[extra] = None;

        assert!(
            rs::recover(&present, code.k, code.r).is_none(),
            "{}: r + 1 lost must be refused, not guessed",
            code.name
        );
    }
}

/// Section 5.1: a data shard carries its item the way an RLC symbol
/// does, and a parity shard carries no prefix of its own.
#[test]
fn a_data_shard_carries_its_item() {
    let item = b"a block of payload";
    let Some(shard) = rs::shard_pack(item, 64) else {
        panic!("an item of {} bytes fits a 64-byte shard", item.len());
    };
    assert_eq!(shard.len(), 64);
    assert_eq!(&shard[2..2 + item.len()], item);
    assert!(shard[2 + item.len()..].iter().all(|b| *b == 0), "padding is zero");

    // The largest item a block carries is shard_len - 2.
    assert!(rs::shard_pack(&[0u8; 62], 64).is_some());
    assert!(rs::shard_pack(&[0u8; 63], 64).is_none());
}

/// Section 5.1: a frame written is the frame read.
#[test]
fn a_data_frame_round_trips() {
    let Some(shard) = rs::shard_pack(b"payload", 32) else {
        panic!("seven bytes fit a 32-byte shard");
    };
    let frame = rs::data_write(7, 3, 8, 2, 0, 0x0BAD_F00D, &shard);
    assert_eq!(frame.len(), 13 + 32);
    assert_eq!(frame[0], 0x01);

    let Some((block, index, k, r, flags, epoch, got)) = rs::data_read(&frame) else {
        panic!("a frame this wrote does not read back");
    };
    assert_eq!((block, index, k, r, flags, epoch), (7, 3, 8, 2, 0, 0x0BAD_F00D));
    assert_eq!(got, shard);

    // Section 5.1: every datagram carries k and r, so a receiver sizes
    // the block from any shard of it.
    let parity_frame = rs::data_write(7, 9, 8, 2, 0x01, 1, &shard);
    let Some((_, index, k, r, flags, _, _)) = rs::data_read(&parity_frame) else {
        panic!("a parity frame does not read back");
    };
    assert_eq!(index, 9);
    assert!(index >= k, "shard indices at or above k are parity");
    assert_eq!(flags & 0x01, 0x01, "the parity bit is set");
    assert_eq!(r, 2);
}

/// Section 5.1: a receiver must discard an outer block whose `d` or
/// `r_outer` is zero, and bit 31 is what separates outer ids from data
/// block ids.
#[test]
fn an_outer_block_id_that_names_nothing_is_refused() {
    // d = 3, r_outer = 2, segment = 0x1234, outer_index = 0x56
    let id = 0x8000_0000u32 | (3 << 27) | (2 << 24) | (0x1234 << 8) | 0x56;
    assert_eq!(rs::outer_id_read(id), Some((3, 2, 0x1234, 0x56)));

    // Bit 31 clear names a data block, not an outer one.
    assert_eq!(rs::outer_id_read(id & 0x7FFF_FFFF), None);

    // A segment with no data blocks, or no parity for them, names
    // nothing decodable. Both fields are one-based on the wire, and a
    // sender must never emit either.
    let no_data = 0x8000_0000u32 | (0 << 27) | (2 << 24) | (0x1234 << 8) | 0x56;
    let no_parity = 0x8000_0000u32 | (3 << 27) | (0 << 24) | (0x1234 << 8) | 0x56;
    assert_eq!(rs::outer_id_read(no_data), None);
    assert_eq!(rs::outer_id_read(no_parity), None);

    // The widest each field goes: d is 4 bits and r_outer is 3.
    let widest = 0x8000_0000u32 | (15 << 27) | (7 << 24) | (0xFFFF << 8) | 0xFF;
    assert_eq!(rs::outer_id_read(widest), Some((15, 7, 0xFFFF, 0xFF)));
}
