//! The C implementation against the frozen vectors.
//!
//! `crates/subetha-cxc/vectors/rlc.txt` is generated by the first
//! implementation and compared against it by a test there, so the file
//! cannot move without that implementation moving. Here it is read as
//! the output of somebody else, and every number in it is checked
//! against C written from the document alone.
//!
//! What agreement buys: two implementations that never shared a line of
//! code produce the same bytes for the same inputs, which is as close as
//! this gets to the document saying what it means. A disagreement would
//! be the more valuable result, because it would name a sentence that
//! reads two ways.
//!
//! The vectors state their source data as arithmetic on the symbol
//! index, so nothing here needs a random source and a failure is always
//! reproducible.

use std::collections::BTreeSet;
use std::path::PathBuf;

use subetha_spec_c as sens;

/// The generator id in `dt`'s high nibble that the document defines.
const GEN_PUBLISHED_TAPS: u8 = 1;

fn vectors_path() -> PathBuf {
    // The vectors live beside the implementation that generates them,
    // and are read here as a file rather than reached through a crate
    // dependency, which this crate deliberately does not have.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("subetha-cxc")
        .join("vectors")
        .join("rlc.txt")
}

/// The vectors' stated source rule, from the file's own header:
///
///     (sid * 131 + b * 17 + 7) & 0xff
fn source_symbol(sid: u32, symbol_len: usize) -> Vec<u8> {
    (0..symbol_len)
        .map(|b| ((sid as usize) * 131 + b * 17 + 7) as u8)
        .collect()
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// One hex byte, or a panic naming what would not read. Nothing in a
/// vectors file is optional enough for a bad byte to become a zero.
fn hex_byte(token: &str) -> u8 {
    match u8::from_str_radix(token, 16) {
        Ok(b) => b,
        Err(e) => panic!("{token:?} in the vectors is not a hex byte: {e}"),
    }
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len()).step_by(2).map(|i| hex_byte(&s[i..i + 2])).collect()
}

/// The value of `key=value` in a whitespace-separated line, or `None`
/// when the line carries no such key.
fn field<'a>(line: &'a str, key: &str) -> Option<&'a str> {
    line.split_whitespace()
        .find_map(|t| t.strip_prefix(key).and_then(|r| r.strip_prefix('=')))
}

/// `key=value` read as a number, decimal or `0x`-prefixed. A value that
/// will not parse is a corrupt vectors file and says so.
fn required(line: &str, key: &str) -> u64 {
    let Some(raw) = field(line, key) else {
        panic!("the vectors line {line:?} names no {key}");
    };
    let parsed = match raw.strip_prefix("0x") {
        Some(digits) => u64::from_str_radix(digits, 16),
        None => raw.parse(),
    };
    match parsed {
        Ok(value) => value,
        Err(e) => panic!("{key}={raw} in the vectors is not a number: {e}"),
    }
}

struct Repair {
    first: u32,
    window: u16,
    dt: u8,
    payload: Vec<u8>,
}

struct Stream {
    name: String,
    density: u8,
    symbol_len: usize,
    sources: u32,
    repairs: Vec<Repair>,
    lost: BTreeSet<u32>,
    recovered: BTreeSet<u32>,
}

/// The lost set the file describes in prose.
///
/// This is the one place the vectors are a sentence rather than data:
/// they say "every 7th id" instead of listing the ids. Reading the
/// phrase is what an independent implementer has to do, so it happens
/// here rather than being worked around, and it is on the list of places
/// the document and its vectors leave something to be interpreted.
fn lost_from_phrase(phrase: &str, sources: u32) -> BTreeSet<u32> {
    let Some(token) = phrase.split_whitespace().find_map(|t| t.strip_suffix("th")) else {
        panic!("the loss pattern {phrase:?} is not one this reads");
    };
    let step: u32 = match token.parse() {
        Ok(n) if n > 0 => n,
        Ok(n) => panic!("the loss pattern {phrase:?} names a step of {n}"),
        Err(e) => panic!("the loss pattern {phrase:?} names no number: {e}"),
    };
    (0..sources).step_by(step as usize).collect()
}

/// The text after a colon, or the whole of it when there is none.
fn after_colon(s: &str) -> &str {
    match s.split_once(':') {
        Some((_, rest)) => rest,
        None => s,
    }
}

fn word(head: &str, at: usize) -> String {
    match head.split_whitespace().nth(at) {
        Some(w) => w.to_string(),
        None => panic!("the section head {head:?} has no word {at}"),
    }
}

fn parse(text: &str) -> (Vec<u8>, Vec<Vec<u8>>, Vec<Stream>) {
    let mut taps = vec![0u8; 64];
    let mut grid: Vec<Vec<u8>> = Vec::new();
    let mut streams: Vec<Stream> = Vec::new();
    let mut section = String::new();

    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        if let Some(rest) = line.strip_prefix('[') {
            let Some(close) = rest.find(']') else {
                panic!("the section line {line:?} does not close its name");
            };
            let head = &rest[..close];
            section = word(head, 0);
            if section == "stream" {
                streams.push(Stream {
                    name: word(head, 1),
                    density: required(line, "density") as u8,
                    symbol_len: required(line, "symbol_len") as usize,
                    sources: required(line, "sources") as u32,
                    repairs: Vec::new(),
                    lost: BTreeSet::new(),
                    recovered: BTreeSet::new(),
                });
            }
            continue;
        }

        if section == "taps" {
            let Some((at, rest)) = line.split_once(':') else {
                panic!("the tap row {line:?} carries no index");
            };
            let base: usize = match at.trim().parse() {
                Ok(n) => n,
                Err(e) => panic!("the tap row index {at:?} is not a number: {e}"),
            };
            for (i, byte) in rest.split_whitespace().enumerate() {
                taps[base + i] = hex_byte(byte);
            }
        } else if section == "coefficients" {
            let row: Vec<u8> = after_colon(line).split_whitespace().map(hex_byte).collect();
            grid.push(row);
        } else if section == "stream" {
            let Some(stream) = streams.last_mut() else {
                panic!("a stream line arrived before any stream: {line:?}");
            };
            if line.starts_with("repair ") {
                let Some(payload) = field(line, "payload") else {
                    panic!("the repair line {line:?} carries no payload");
                };
                stream.repairs.push(Repair {
                    first: required(line, "first") as u32,
                    window: required(line, "window") as u16,
                    dt: required(line, "dt") as u8,
                    payload: unhex(payload),
                });
            } else if let Some(rest) = line.strip_prefix("lost ") {
                stream.lost = lost_from_phrase(after_colon(rest), stream.sources);
            } else if let Some(rest) = line.strip_prefix("recovered ") {
                let mut set = BTreeSet::new();
                for id in after_colon(rest).split_whitespace() {
                    match id.parse() {
                        Ok(n) => {
                            set.insert(n);
                        }
                        Err(e) => panic!("the recovered id {id:?} is not a number: {e}"),
                    }
                }
                stream.recovered = set;
            }
        }
        // The generators section is a legend for human readers and
        // carries nothing this checks, so lines outside the three
        // sections above are passed over deliberately.
    }

    (taps, grid, streams)
}

fn load() -> (Vec<u8>, Vec<Vec<u8>>, Vec<Stream>) {
    let path = vectors_path();
    let text = match std::fs::read_to_string(&path) {
        Ok(t) => t,
        Err(e) => panic!("the vectors at {} could not be read: {e}", path.display()),
    };
    parse(&text)
}

/// Section 4.4: the table the document prints, byte for byte.
#[test]
fn the_tap_table_is_the_one_the_document_prints() {
    let (taps, _, _) = load();
    assert_eq!(taps.len(), 64, "the table has 64 entries");
    for (place, expected) in taps.iter().enumerate() {
        assert_eq!(sens::tap(place), *expected, "tap at place {place}");
    }
    // Past the table a place takes no coefficient at all, which is what
    // keeps a window wider than 64 from multiplying its oldest symbols
    // by whatever happens to follow the array.
    assert_eq!(sens::tap(64), 0);
    assert_eq!(sens::tap(1000), 0);
}

/// Section 4.4: every place at every density.
///
/// This is the check that separates the two readings of density. Read
/// as a reach into the window, density 0 would take only place 0; read
/// as a fraction of it, as the document says, it takes places 0, 16, 32
/// and 48.
#[test]
fn every_coefficient_matches_the_grid() {
    let (_, grid, _) = load();
    assert_eq!(grid.len(), 16, "one row per density, 0 to 15");
    for (density, row) in grid.iter().enumerate() {
        assert_eq!(row.len(), 64, "a row covers places 0 to 63");
        for (place, expected) in row.iter().enumerate() {
            assert_eq!(
                sens::coefficient(place, density as u8),
                *expected,
                "coefficient at place {place}, density {density}"
            );
        }
    }
}

/// Section 4.2: every repair in every geometry, byte for byte.
#[test]
fn every_repair_payload_matches() {
    let (_, _, streams) = load();
    assert!(!streams.is_empty(), "the vectors carry at least one stream");

    let mut checked = 0usize;
    for stream in &streams {
        for repair in &stream.repairs {
            assert_eq!(
                repair.dt >> 4,
                GEN_PUBLISHED_TAPS,
                "{}: the vectors use the generator the document defines",
                stream.name
            );
            assert_eq!(
                repair.dt & 0x0F,
                stream.density,
                "{}: dt's low nibble is the stream's density",
                stream.name
            );

            // Oldest first, newest last, which is where place comes from.
            let window: Vec<Vec<u8>> = (0..u32::from(repair.window))
                .map(|i| source_symbol(repair.first + i, stream.symbol_len))
                .collect();

            let Some(frame) = sens::repair_write(0, 0, repair.first, repair.dt, &window) else {
                panic!("{}: the generator in {:#04x} was refused", stream.name, repair.dt);
            };
            let payload = &frame[20..];

            assert_eq!(
                hex(payload),
                hex(&repair.payload),
                "{}: repair over [{}, {}) at dt {:#04x}",
                stream.name,
                repair.first,
                repair.first + u32::from(repair.window),
                repair.dt
            );
            checked += 1;
        }
    }
    assert!(checked >= 100, "only {checked} repairs checked");
}

/// Section 4.2 and 4.4: the same symbols come back from the same losses.
///
/// A decoder's choice of which repair to use is its own, so what is
/// compared is the set of ids recovered, which is a property of the code
/// rather than of the decoder. A different set would mean the two
/// implementations disagree about which symbols a repair covers, which
/// is the thing the document defines.
#[test]
fn the_same_symbols_recover_from_the_same_losses() {
    let (_, _, streams) = load();

    for stream in &streams {
        if stream.lost.is_empty() {
            continue;
        }

        let mut held: Vec<Option<Vec<u8>>> = (0..stream.sources)
            .map(|sid| {
                (!stream.lost.contains(&sid)).then(|| source_symbol(sid, stream.symbol_len))
            })
            .collect();

        let mut recovered: BTreeSet<u32> = BTreeSet::new();
        // Recovering one symbol can be what leaves another repair with a
        // single hole, so this runs until a pass finds nothing.
        loop {
            let mut progress = false;
            for repair in &stream.repairs {
                let ids: Vec<u32> =
                    (0..u32::from(repair.window)).map(|i| repair.first + i).collect();
                // Section 4.4: a coefficient of zero means the symbol
                // does not enter the equation, so a hole only counts
                // where the coefficient is nonzero. Counting holes
                // across the whole window instead gives up on every
                // sparse repair that could still solve: at density 0 a
                // window of 48 carries three symbols in its equation.
                let holes: Vec<u32> = ids
                    .iter()
                    .copied()
                    .enumerate()
                    .filter(|(i, id)| {
                        let place = usize::from(repair.window) - 1 - i;
                        sens::coefficient(place, repair.dt & 0x0F) != 0
                            && held[*id as usize].is_none()
                    })
                    .map(|(_, id)| id)
                    .collect();
                if holes.len() != 1 {
                    continue;
                }
                let window: Vec<Option<Vec<u8>>> =
                    ids.iter().map(|id| held[*id as usize].clone()).collect();
                // A `None` here is an answer, not a failure: the hole's
                // coefficient is zero, so this repair never covered it.
                // Another repair may.
                let Some(symbol) = sens::repair_recover(&repair.payload, &window, repair.dt)
                else {
                    continue;
                };
                let id = holes[0];
                assert_eq!(
                    hex(&symbol),
                    hex(&source_symbol(id, stream.symbol_len)),
                    "{}: symbol {id} recovered to the wrong bytes",
                    stream.name
                );
                held[id as usize] = Some(symbol);
                recovered.insert(id);
                progress = true;
            }
            if !progress {
                break;
            }
        }

        assert_eq!(
            recovered, stream.recovered,
            "{}: recovered a different set of ids than the vectors state",
            stream.name
        );
    }
}

/// Section 4.3: an item survives packing and unpacking, and the padding
/// is zero so it contributes nothing to a repair's sum.
#[test]
fn a_symbol_carries_its_item_and_pads_with_zero() {
    let item = b"the quick brown fox";
    let Some(symbol) = sens::symbol_pack(item, 64) else {
        panic!("an item of {} bytes fits a 64-byte symbol", item.len());
    };
    assert_eq!(symbol.len(), 64);
    assert_eq!(&symbol[2..2 + item.len()], item);
    assert!(
        symbol[2 + item.len()..].iter().all(|b| *b == 0),
        "the padding is zero"
    );
    assert_eq!(sens::symbol_unpack(&symbol), item);

    // The document states the constraint as length + 2 <= symbol_len.
    assert!(sens::symbol_pack(&[0u8; 62], 64).is_some());
    assert!(sens::symbol_pack(&[0u8; 63], 64).is_none());
}

/// Section 4.3: a corrupt length yields a short item rather than a read
/// past the end.
#[test]
fn a_symbol_clamps_a_length_it_cannot_hold() {
    let mut symbol = vec![0u8; 16];
    symbol[0] = 0xff;
    symbol[1] = 0xff;
    let item = sens::symbol_unpack(&symbol);
    assert_eq!(item.len(), 14, "clamped to the buffer actually held");
}

/// Section 4.1, 4.5 and 4.6: a frame written is the frame read.
#[test]
fn frames_round_trip() {
    let Some(symbol) = sens::symbol_pack(b"payload", 32) else {
        panic!("seven bytes fit a 32-byte symbol");
    };
    let frame = sens::data_write(0x0123_4567_89ab_cdef, 42, 1234, &symbol);
    assert_eq!(frame.len(), 17 + 32);
    assert_eq!(frame[0], 0x0A);
    let Some((conn, sid, us, got)) = sens::data_read(&frame) else {
        panic!("a frame this wrote does not read back");
    };
    assert_eq!(conn, 0x0123_4567_89ab_cdef);
    assert_eq!(sid, 42);
    assert_eq!(us, 1234);
    assert_eq!(got, symbol);

    let ack = sens::ack_write(7, 0b1011);
    assert_eq!(ack.len(), 13);
    assert_eq!(sens::ack_read(&ack), Some((7, 0b1011)));

    let nak = sens::nak_write(&[3, 9, 27]);
    assert_eq!(nak.len(), 1 + 12);
    assert_eq!(sens::nak_read(&nak), vec![3, 9, 27]);

    // Section 4.5: ids are read until fewer than four bytes remain, so a
    // trailing partial id is ignored rather than making the frame
    // invalid.
    let mut ragged = nak.clone();
    ragged.push(0xAA);
    ragged.push(0xBB);
    assert_eq!(sens::nak_read(&ragged), vec![3, 9, 27]);
}

/// Section 4.4: a receiver that cannot reproduce a generator must drop
/// the repair rather than decode with different coefficients.
#[test]
fn a_generator_this_cannot_reproduce_is_refused() {
    let window: Vec<Vec<u8>> = (0..4u32).map(|i| source_symbol(i, 16)).collect();
    // Generator 0 is per-repair generation, which the document does not
    // define.
    assert!(sens::repair_write(0, 0, 0, 0x0F, &window).is_none());
    // And one the document has never assigned.
    assert!(sens::repair_write(0, 0, 0, 0x7F, &window).is_none());

    let present: Vec<Option<Vec<u8>>> = window.iter().cloned().map(Some).collect();
    assert!(sens::repair_recover(&[0u8; 16], &present, 0x0F).is_none());
}

/// Section 2: the field is the one the document names.
#[test]
fn the_field_is_the_documents_field() {
    // Every nonzero element has an inverse that multiplies back to one,
    // which holds only if the reduction polynomial is the right one.
    for a in 1u16..=255 {
        let a = a as u8;
        assert_eq!(sens::gf_mul(a, sens::gf_inv(a)), 1, "inverse of {a:#04x}");
    }
    assert_eq!(sens::gf_mul(0, 0xff), 0);
    assert_eq!(sens::gf_mul(1, 0xff), 0xff);
    // The reduction itself: 0x80 doubled overflows and reduces by the
    // polynomial's low byte, which is 0x1D.
    assert_eq!(sens::gf_mul(0x80, 0x02), 0x1D);
}
